#!/usr/bin/env python3
"""Discover HTML source artifacts and compose deterministic static pages."""

from __future__ import annotations

import argparse
import difflib
import os
import sys
import threading
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "site" / "content"
FRAGMENTS = ROOT / "site" / "fragments"
REQUIRED_LANGUAGES = ("en", "el")
SOURCE_PATHS = (Path(__file__), CONTENT, FRAGMENTS)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8").rstrip()


def pages() -> list[tuple[Path, str, Path]]:
    """Discover source artifacts; English and Greek remain required per route."""
    discovered: list[tuple[Path, str, Path]] = []
    for source in sorted(CONTENT.rglob("index.*.html")):
        lang = source.name.removeprefix("index.").removesuffix(".html")
        if not lang:
            continue
        relative = source.relative_to(CONTENT).with_name("index.html")
        output = relative if lang == "en" else Path(lang.lower()) / relative
        discovered.append((source, lang, ROOT / output))

    sources = {(source.parent, lang) for source, lang, _ in discovered}
    missing = [
        str(directory.relative_to(CONTENT) / f"index.{lang}.html")
        for directory, _ in sorted(sources, key=lambda item: str(item[0]))
        for lang in REQUIRED_LANGUAGES
        if (directory, lang) not in sources
    ]
    if missing:
        raise ValueError("Missing language pair: " + ", ".join(missing))
    if not discovered:
        raise ValueError("No page sources found")
    return discovered


def fragment(name: str, lang: str) -> str:
    return read(FRAGMENTS / f"{name}.{lang}.html")


def compile_page(source: Path, lang: str) -> str:
    return (
        "<!doctype html>\n"
        "<!-- Generated by site/build.py; edit site/content or site/fragments. -->\n"
        f'<html lang="{lang}">\n'
        f'{fragment("head", lang)}\n'
        "  <body>\n"
        f'{fragment("header", lang)}\n'
        f'{read(source)}\n'
        f'{fragment("footer", lang)}\n'
        "  </body>\n"
        "</html>\n"
    )


def build_site(check: bool) -> int:
    stale: list[str] = []
    for source, lang, target in pages():
        compiled = compile_page(source, lang)
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current == compiled:
            continue
        if check:
            relative = str(target.relative_to(ROOT))
            stale.append(relative)
            print("".join(difflib.unified_diff(
                current.splitlines(True),
                compiled.splitlines(True),
                fromfile=relative,
                tofile=f"compiled/{relative}",
            ))[:4000])
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(compiled, encoding="utf-8", newline="\n")
    if stale:
        print("Generated pages are stale: " + ", ".join(stale))
        return 1
    print("Generated pages are deterministic and current." if check else "Compiled discovered static pages.")
    return 0


def source_fingerprint() -> tuple[tuple[str, int, int], ...]:
    files: list[Path] = []
    for source in SOURCE_PATHS:
        files.extend(path for path in source.rglob("*") if path.is_file()) if source.is_dir() else files.append(source)
    return tuple(
        (str(path.relative_to(ROOT)), stat.st_mtime_ns, stat.st_size)
        for path in sorted(files)
        for stat in (path.stat(),)
    )


def terminal_link(url: str) -> str:
    if sys.stdout.isatty() and os.environ.get("TERM", "") != "dumb":
        return f"\033]8;;{url}\033\\{url}\033]8;;\033\\"
    return url


def serve(host: str, port: int) -> int:
    if build_site(check=False):
        return 1
    state = {"fingerprint": source_fingerprint()}
    build_lock = threading.Lock()

    class RebuildingHandler(SimpleHTTPRequestHandler):
        def _rebuild_if_needed(self) -> None:
            with build_lock:
                current = source_fingerprint()
                if current == state["fingerprint"]:
                    return
                if build_site(check=False):
                    raise RuntimeError("Build failed")
                state["fingerprint"] = current

        def do_GET(self) -> None:
            try:
                self._rebuild_if_needed()
            except (OSError, RuntimeError, ValueError) as error:
                self.send_error(500, f"Build failed: {error}")
                return
            super().do_GET()

        def do_HEAD(self) -> None:
            try:
                self._rebuild_if_needed()
            except (OSError, RuntimeError, ValueError) as error:
                self.send_error(500, f"Build failed: {error}")
                return
            super().do_HEAD()

    display_host = "127.0.0.1" if host in {"0.0.0.0", "::"} else host
    url = f"http://{display_host}:{port}/"
    server = ThreadingHTTPServer(
        (host, port),
        lambda *args, **kwargs: RebuildingHandler(*args, directory=str(ROOT), **kwargs),
    )
    print(f"Preview: {terminal_link(url)}", flush=True)
    print("Edit a source file, then refresh the browser. Press Ctrl+C to stop.", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("command", nargs="?", choices=("build", "serve"), default="build")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8080)
    args = parser.parse_args()
    if args.command == "serve":
        if args.check:
            parser.error("--check cannot be used with serve")
        raise SystemExit(serve(args.host, args.port))
    try:
        raise SystemExit(build_site(args.check))
    except (OSError, ValueError) as error:
        parser.error(str(error))
